### ISSUE TITLE
Termi-Lua.Opencalc issues and enhancements

### ISSUE THREAD

**Issue by hahahahacker2009** [ringwormGO-organization/Termi-Lua#2]
Enhancement: Add separates functions to do their own work, for example Calculator's function when people call the calculator command
Enhancement: Termi-Lua.Opencalc, Termi-Lua.OpenGeocalc: Print when asking about numbers.

Enhancement: Create a command-list variable (array), when user enter a command, just check if the command exist in the command list.
Issue: Termi-Lua.AllCommands: Response if user put in the unexpected value

![image](https://user-images.githubusercontent.com/86903124/153407636-cf7b97a2-a326-42a5-9dfb-b1169311fd8d.png)

Hope this can improves the project!

**Comment by Andrej123456789** [comment]
![image](https://user-images.githubusercontent.com/83548580/153645625-152bdee3-afbf-42c9-9a5b-9bb8dbe886c7.png)

**Comment by Andrej123456789** [comment]
My output

**Comment by StjepanBM1** [comment]
To comment on your issue:

1. Photo>
If you think that you can calculate r+r and that it would show a result?, I have bad news. No calculator can calculate r+r

2. Photo>
In what universe will ff make a valid output? Geo-calc is a geometric calculator, and please can you explain what did you want to do with rr?

To conclude:
These issues can simply dumb user mistakes.

**Comment by Andrej123456789** [comment]
In maths you can enter `e`

**Comment by StjepanBM1** [comment]
Yes I know that but what is r+r?

**Comment by Andrej123456789** [comment]
Check input and send message `Operation invalid`

**Comment by StjepanBM1** [comment]
Yea will add that in Version 0.0.3

**Comment by Andrej123456789** [comment]
Ok but then don't close this issue

**Comment by hahahahacker2009** [comment]
> To comment on your issue:
> 
> 1. Photo>
>    If you think that you can calculate r+r and that it would show a result?, I have bad news. No calculator can calculate r+r
> 2. Photo>
>    In what universe will ff make a valid output? Geo-calc is a geometric calculator, and please can you explain what did you want to do with rr?
> 
> To conclude: These issues can simply dumb user mistakes.

still need to tell the user if there inputs are invalid

**Comment by StjepanBM1** [comment]
Well, that is the plan for version 0.0.3 but still I do think that common user will know how to use a calculator

**Comment by hahahahacker2009** [comment]
> Well, that is the plan for version 0.0.3 but still I do think that common user will know how to use a calculator

hope that 0.0.3 will be release soon
