### ISSUE TITLE
Colors don't work on Windows

### ISSUE THREAD

**Issue by StjepanBM1** [ringwormGO-organization/Termi-Lua#4]
Terminal colors don't work on @Microsoft Windows.

**Comment by Andrej123456789** [comment]
Fixed with https://github.com/ringwormGO-organization/Termi-Lua/commit/201b334ae644ac5de3e48871841a54134ec3f77a

**Comment by Andrej123456789** [comment]
Actually issue isn't fixed but if your Windows supports Windows Terminal, just use that terminal
